/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedSummarizeNotesImport } from './routes/_authed/summarize-notes'
import { Route as AuthedNotesImport } from './routes/_authed/notes'

// Create/Update Routes

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedSummarizeNotesRoute = AuthedSummarizeNotesImport.update({
  id: '/summarize-notes',
  path: '/summarize-notes',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedNotesRoute = AuthedNotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_authed/notes': {
      id: '/_authed/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthedNotesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/summarize-notes': {
      id: '/_authed/summarize-notes'
      path: '/summarize-notes'
      fullPath: '/summarize-notes'
      preLoaderRoute: typeof AuthedSummarizeNotesImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedNotesRoute: typeof AuthedNotesRoute
  AuthedSummarizeNotesRoute: typeof AuthedSummarizeNotesRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedNotesRoute: AuthedNotesRoute,
  AuthedSummarizeNotesRoute: AuthedSummarizeNotesRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/notes': typeof AuthedNotesRoute
  '/summarize-notes': typeof AuthedSummarizeNotesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/notes': typeof AuthedNotesRoute
  '/summarize-notes': typeof AuthedSummarizeNotesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/notes': typeof AuthedNotesRoute
  '/_authed/summarize-notes': typeof AuthedSummarizeNotesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/notes' | '/summarize-notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/notes' | '/summarize-notes'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/notes'
    | '/_authed/summarize-notes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/notes",
        "/_authed/summarize-notes"
      ]
    },
    "/_authed/notes": {
      "filePath": "_authed/notes.tsx",
      "parent": "/_authed"
    },
    "/_authed/summarize-notes": {
      "filePath": "_authed/summarize-notes.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
